### ISSUE TITLE
deployClusterTask has the wrong name in task.prod.json

### ISSUE THREAD

**Issue by MrCandle** [DataThirstLtd/databricks.vsts.tools#13]
When you add the task to azure-pipelines.yml the following name is added to the task: databricksDeployScripts@0. The same name is being used by the databricksDeployScripts task.

The workaround for now was to use the deployClusterTask id directly: 14e92359-f063-4955-b3c0-96a5523b71f4.

**Comment by simondmorias** [comment]
Thanks for raising. I hope to release this fix by the end of the week.
