### ISSUE TITLE
Databricks Deploy Cluster task outputs invalid variables

### ISSUE THREAD

**Issue by lapellaniz** [DataThirstLtd/databricks.vsts.tools#18]
Description:

"Databricks Deploy Cluster" task is returning an invalid value for the cluster ID. Sometimes the output variable will contain the full JSON REST response payload returned from the create call, and sometimes the variable is empty.

Actual:
The Azure DevOps variable $(DatabricksClusterId) outputs the following:

```
@{cluster_id=0403-200058-slaoe570}
```

For existing clusters, even if the JSON definition doesn't change, the logic in the task finds the cluster but also determines that the cluster has changed. 

Expected:

- Azure DevOps variable $(DatabricksClusterId) should output just the cluster id. In this example "0403-200058-slaoe570"
- When a cluster is found and there are no changes to the JSON config, an edit should not be sent.

**Comment by MrCandle** [comment]
Same thing is happening to me

**Comment by MrCandle** [comment]
I was looking at the code and it says the following:
`"description": "This is the ClusterId created/edited for use in other requests reference as $(ClusterId) or $env:ClusterId in PS Scripts"`

It was also empty in my case

**Comment by MrCandle** [comment]
According to the powershell code, it should still be DatabricksClusterId:
`Write-Host "##vso[task.setVariable variable=DatabricksClusterId;]$ClusterId"`
`Write-Host "##vso[task.setVariable variable=Extension.DatabricksClusterId;]$ClusterId"`

**Comment by simondmorias** [comment]
Deployed a fix for this. Thanks for reporting.
