### ISSUE TITLE
[error]The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by Venka619** [DataThirstLtd/databricks.vsts.tools#24]
I have build my Script on Azure Databricks.Connected my script to  devops, build the script and created a release pipeline.
Inside my release pipeline I have added (Databricks DBFS File Deployment). Below is the error been thrown.

[error]The remote server returned an error: (403) Forbidden.

I have tried using the (Databricks Notebook Deployment) and it worked well.
Can someone help me out whether I need to add some extra setup to the release pipeline because it seems to be an authorization access issue. 
Please help me out

**Comment by simondmorias** [comment]
Could you provide details of the target path you have specified? 
Is there anything else in the logs?

**Comment by Venka619** [comment]
@simondmorias . Thanks for the quick respnonse. I tried with multiple target paths like (/(root location), /Filestore, /mnt (the path on which I mounted my blob storage).
This is the only thing that I see in the logs generated by the release pipeline is the remote server error.

**Comment by Venka619** [comment]
@simondmorias The issue is solved. My token was expired due to which it was throwing this error
