### ISSUE TITLE
Unable to deploy Notebook 

### ISSUE THREAD

**Issue by chandra9787** [DataThirstLtd/databricks.vsts.tools#28]
Im getting the Below error when I try to deploy the notebook 

**No Match was found fo the Specified search criteria and module name 'ThreadJob'**

Please Help

**Comment by simondmorias** [comment]
Are you running on a self hosted agent or Microsoft hosted agent?

**Comment by chandra9787** [comment]
Yes, We are using Self hosted agent,

**Comment by simondmorias** [comment]
It must be missing thread job then. 

Login to the agent over RDP

open windows powershell as admin

Install-module ThreadJob.

**Comment by simondmorias** [comment]
It should be there by default though. So many be your powershell version is old?

**Comment by chandra9787** [comment]
Thanks Simon, will give a try. 
Once installed the mentioned module, does the agent need internet connection to run the Databricks notebook deploy task?

**Comment by simondmorias** [comment]
Well it will need access to your databricks instance at least. The rest of the powershell module has dependencies included so it should t need access to anything else as far as I know.
