### ISSUE TITLE
No match was found for the specified search criteria and module name 'ThreadJob'.

### ISSUE THREAD

**Issue by vaidhyb** [DataThirstLtd/databricks.vsts.tools#35]
Hi We are using DBFS Binary file deployment task in one of the Azure DevOps release to deploy our binary files.  From today morning onwards we are facing the below mentioned error in deployment. We could not find any troubleshooting steps. Please reply us on the below issue?

"No match was found for the specified search criteria and module name 'ThreadJob'. Try Get-PSRepository to see all available registered module repositories."

Thanks
Vaidhyanathan
![image](https://user-images.githubusercontent.com/29790806/97672013-586bf080-1aaf-11eb-82b5-f95c6bba6e67.png)

**Comment by simondmorias** [comment]
I believe this is due to powershell gallery being offline and the task cannot download dependencies. 
Hopefully they will restore service shortly. Please check their website.

**Comment by PaulJar** [comment]
Hello @simondmorias ,

Thank you for your help.
Do you know where we can check on their site ?
I didn't find anything...

Thanks in advance !

**Comment by hiteshchouhan90** [comment]
Does anyone know when will this issue with powershellgallery be resolved?

**Comment by ambarishprabhu** [comment]
Hey there,
Is there any workaround you could provide in the interim? We use these tasks to deploy notebooks to production workspaces. Help here would be much appreciated!
Thanks

**Comment by CZRam** [comment]
Looks like powershell gallery has a [status page](https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md) on GitHub currently showing a service outage, hopefully they will update soon:

**Comment by simondmorias** [comment]
Appears all solved now. Any issues please reopen.

**Comment by Ashish-Jovial** [comment]
I am facing the same issue today when I am deploying data bricks code using the Azure DevOps CD pipeline.

No match was found for the specified search criteria and module name 'ThreadJob'. Try Get-PSRepository to see all available registered module repositories.
