### ISSUE TITLE
The term 'Start-ThreadJob' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by LKShankarKarthik** [DataThirstLtd/databricks.vsts.tools#38]
In our scenario, we use Data Thirst's Taks in our DevOps pipeline to perform Databricks Notebook Deployment. Pipeline was all working fine when we first configured it few months before. But when we executed the pipeline last week to update the environment, we started gettting this new error. Can we please review and let us know what could be the reason for this?

[Deploy Databricks error.docx](https://github.com/DataThirstLtd/databricks.vsts.tools/files/6046425/Deploy.Databricks.error.docx)

**Comment by simondmorias** [comment]
I assume you are running on a self hosted vm. You need to install ThreadJob in a powershell window as admin.

________________________________

**Comment by Ashish-Jovial** [comment]
Hi Team,

Any update on this issue?

**Comment by simondmorias** [comment]
The answer is above. On a self hosted agent you need to install threadjob. Make sure you do it from a windows powershell window running as admin.
